version: "3.4"
services:
  app:
    build:
      args:
        user: docker
        uid: 1000
      context: ./docker/php-fpm
    container_name: _app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - _app

  nginx:
    image: nginx:1.17-alpine
    container_name: _nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/configs/nginx:/etc/nginx/conf.d
    networks:
      - _app

  db:
    image: mysql:5.7
    container_name: _db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/data/db:/var/lib/mysql
    networks:
      - _app

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: _pma
    links:
      - db
    ports:
      - "8765:80"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - _app

networks:
  _app:
    driver: bridge
    ipam:
      driver: default